Scripts/ecommerce/cart/urls.py
from django.conf.urls import url # import django url helper class
from . import views # import views from cart views.py file

app_name = 'cart' # create a namespace for our cart application called ‘cart’

# we create a list of url patterns
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'), # define a url that will display cart detail page
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'), # define url to add items to the cart
    url(r'remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'), #  define url to remove items from our cart
]

Scripts/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static # import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')), # add urls patterns from our cart application
    path('orders/', include('orders.urls')), # Remember, orders url must be placed before the shop urls pattern and that’s why we have added orders url above shop urls
    path('', include('shop.urls')), # included our shop application urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # serve our static file by adding our MEDIA_URL and MEDIA_ROOT settings.
# This is only done in development environment.

Scripts/ecommerce/shop/urls.py
from django.conf.urls import url # import url from django urls
from . import views # import methods in our views.py file

app_name = 'shop' # create a namespace for our shop application.

#  create a python list for our url patterns for our application.
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'), # This url is mapped to our product_list method and it will fetch all products

    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    # This url is also mapped to product_list method but we pass category_slug as our parameter hence, products we be filtered by a given category.

    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    # This url is mapped to product_detail method and this will fetch a specific product.
]

Scripts/ecommerce/shop/models.py
from django.db import models
from django.urls import reverse # import reverse function from django urls

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    ceated_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    # create get_absolute_url method to create SEO-friendly url from our shop url patterns.
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),) #  using index_together meta option to specify an index for id and slug fields. This will help improve performances of queries.

    def __str__(self):
        return self.name

    # created get_absolute_url method to create SEO-friendly url from our shop url patterns. Remember the app_name we defined in the shop app urls.py file, that is how we use it in the get_absolute_url()
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

Scripts/ecommerce/shop/views.py
from django.shortcuts import render, get_object_or_404 # importing shortcut methods to render my template and to check whether an object is found or to raise a 404 error.

from .models import Category, Product # importing my Category and Product model.

from cart.forms import CartAddProductForm # import CartAddProductForm package from cart forms


 # creating a function called product_list which I will use to display a list of products. In this function, I am also passing a second parameter called category_slug=None which I will use if products are filtered using a given category by our users.
def product_list(request, category_slug=None):
    category = None # specifying category is equal to none, in order to show the list of products without filtering them by any category.

    categories = Category.objects.all() # querying and fetching all the categories from my database

    products = Product.objects.filter(available=True) # fetching all the products from my database which are available by passing(available=True) filter to my queryset.


    # creating an if statement to optionally filter the products based on the category_slug parameter passed from my url.
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug) # creating a variable called category and creating a queryset to the Category model and filtering the result with category_slug parameter.

        products = Product.objects.filter(category=category) # creating a queryset to fetching products and filtering the products based on the category from line 12


   # simply creating a data dictionary to pass to my template.
    context = {
        'category':category,
        'categories':categories,
        'products':products
    }
    return render(request, 'shop/product/list.html', context) #  rendering a template called list.html which there is yet to create and also passing data context.


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True) # creating queryset and I am using id and slug to retrieve product instance. That is also checking whether the product is available or not.
    # We can get this instance by just the ID since it’s a unique attribute. However, we include the slug in the URL to build SEO-friendly URLs for products.
    
    cart_product_form = CartAddProductForm() #  created our cart_product_form object

    # creating a dictionary of my data in order to pass this data to my template using a single context.
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/product/detail.html', context) # rendering a template called detail.html which there is yet to create and passing the context data to this template.

Scripts/ecommerce/shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}On-line Shop{% endblock %}</title>

        <!-- loading bootstrap.min.css and styles.css in this file. -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    <body>
        <!--  including our navbar.html file so that it’s available for use -->
        {% include 'shop/navbar.html' %}

        <!-- creat a bootstrap container -->
        <div class="container">

            <!-- created bootstrap row -->
            <div class="row" style="margin-top: 6%">

                <!-- create a bootstrap button -->
                 <button class="btn btn-info pull-right">

                    <!-- check whether our cart has items and display the content. If the cart is empty, we display “Your cart is empty”.  -->
                    {% with totail_items=cart|length %}
                        {% if cart|length > 0 %}
                            My Shopping Order:

                            <!-- create a link to our cart detail page -->
                            <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                                {{ totail_items }} item {{ totail_items|pluralize }}, ${{ cart.get_total_price }}
                            </a>
                            
                            {% else %}
                            Your cart is empty.
                        {% endif %}
                    {% endwith %}

                 </button>

            </div>

        </div>

        {% block content %}

        {% endblock %}

        <!-- loading jquery and bootstrap javascript in this file. -->
        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    </body>
</html>

Scripts/ecommerce/shop/templates/shop/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Anti J.S.Park</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          {% if request.user.is_authenticated %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="">logout</a></li>
            {% else %}
          <li class="divider"></li>
          <li><a href="#" style="color: #ffffff">Sign in</a></li>
         <li><a href="#" style="color: #ffffff">Sign up</a></li>
        </ul>
         {% endif %}
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>